### ISSUE TITLE
multilingual: Shared resource discarded if same bundle does not exist in default content language

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#12107]
Similar to #12079, but there's no ambiguity in this case: we should not discard the page resource.

Below, `en` is the default content language.

```text
content/
└── s1/
    ├── p1/
    │   ├── a.txt
    │   └── index.de.md  <-- non-default content language, no matching bundle in english
    ├── _index.de.md
    └── _index.en.md
```

Expected (v0.122.0)

```text
public/
├── de/
│   ├── s1/
│   │   ├── p1/
│   │   │   ├── a.txt      <-- this is missing in v0.123.1 see below
│   │   │   └── index.html
│   │   └── index.html
│   └── index.html
├── en/
│   ├── s1/
│   │   └── index.html
│   └── index.html
└── index.html
```

Actual (v0.123.1)

```text
public/
├── de/
│   ├── s1/
│   │   ├── p1/
│   │   │   └── index.html
│   │   └── index.html
│   └── index.html
├── en/
│   ├── s1/
│   │   └── index.html
│   └── index.html
└── index.html
```

<details>
<summary>failing test case</summary>

```go
func TestFoo(t *testing.T) {
	t.Parallel()

	files := `
-- hugo.toml --
disableKinds = ['rss','sitemap','taxonomy','term']
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
[languages.en]
[languages.de]
-- layouts/_default/single.html --
{{ .RelPermalink }}
-- layouts/_default/list.html --
{{ .RelPermalink }}
-- content/s1/_index.de.md --
---
title: s1 (de)
---
-- content/s1/_index.en.md --
---
title: s1 (en)
---
-- content/s1/p1/index.de.md --
---
title: s1/p1 (de)
---
-- content/s1/p1/a.txt --
irrelevant
`

	b := hugolib.Test(t, files)

	b.AssertFileExists("public/de/s1/index.html", true)
	b.AssertFileExists("public/de/s1/p1/index.html", true)
	b.AssertFileExists("public/de/s1/p1/a.txt", true) // failing test

	b.AssertFileExists("public/en/s1/index.html", true)
	b.AssertFileExists("public/en/s1/p1/index.html", false)
	b.AssertFileExists("public/en/s1/p1/a.txt", false)
}
```
</details>
<br>

References:

- <https://discourse.gohugo.io/t/resources-getmatch-issue-in-0-123/48619>
- <https://github.com/gohugoio/hugo/issues/12189#issuecomment-1973705053> (item 5)

**Comment by bep** [comment]
```
content/
└── s1/
    ├── p1/
    │   ├── a.txt <--- this is by definition an English resource
    │   └── index.de.md  <-- non-default content language, no matching bundle in english
    ├── _index.de.md
    └── _index.en.md
```

I'm sure about this.

* In 0.122.0 we created missing bundle headers for "dangling resources"
* The simplification in 0.123.0 was made partly to prepare for other content data sources, and we don't want to have to "look at the whole thing" to determine where a piece of content belongs.
* `a.txt`  is English. I don't want to open up to saying that it may change language depending on some other file presence.

**Comment by jmooring** [comment]
> are you explicitly and definitely saying a.json and a.jpg are English

No. They are tied to the default content language as specified in your site configuration, falling back to `en` if not specified in site configuration.

**Comment by nekr0z** [comment]
As I see it, this is a fundamental divergence from the mutlilingual logic in Hugo.

The basic multilingual logic for missing translations is, as documented: "If a string does not have a translation for the current language, Hugo will use the value from the default language. If no default value is set, an empty string will be shown." Effectively: `_string in the language_ | default _string in default language_ | default ""`.

Up until 0.122, the same logic applied to resources. Here, this logic is broken.

While the _page_ in the default language does not exist, the _resource_ (in the default language) does exist, is explicitly called (from the page in another language), and _should_ be used as a fallback, instead of falling right through to the empty value.

**Comment by markdumay** [comment]
To add my two cents, I noticed this behavior applies to image resources as well. My site - available in both English (default) and Dutch - contains several pages that use page resources. This is done mainly to improve the site's asset management (these "local" images are very specific to a blog post, and are not reused elsewhere).

Consider the following example:

```
.
└── content
    └── blog
        └── my-first-post
            ├── img
            │   └── image1.jpg
            └── index.nl.md
```

In this setup, `image1.jpg` is not available as page resource to `index.nl.md`. When I add `index.en.md`, the image does become available to both translated pages. IMHO, these (image) resources should be available regardless if a page in the default language is available.

**Comment by brmassa** [comment]
Here too. It breaks my site!!!

My blog has 2 languages and most posts are in only one of them. If there is no default langauge post, all the images are ignored.

`{{ .Resoureces }}` is returning `[]` if no default index.md is present

**Comment by bep** [comment]
I will take one more look at this later today and see if I can make "an exception" for content files (which is what we have today), but some goals with this new setup was to 

* Make it easy to insert/update content without having to know too much about the surrounding context.
* Make that not dependent on any order so we could do it concurrently.

**Comment by CXwudi** [comment]
I would like to share my circumstance as well. My folder structure is as following:

```
.
└── content
    └── posts
        └── my-first-post
            ├── img.png
            ├── index.en.md
            └── index.zh-cn.md
```

The default language is set to English.

I can see that `img.png` is properly showing in `index.en.md` but not `index.zh-cn.md`

**Comment by jmooring** [comment]
@CXwudi Your problem is not related to this issue. Please create a new issue.

**Comment by CXwudi** [comment]
Done at https://github.com/gohugoio/hugo/issues/12244

**Comment by brmassa** [comment]
0.125.3 the problem persists... @bep, @jmooring, reopen it please.

`{{ .Resources.ByType "iamges" }}` will return `[]` if there is only a non-default page.

**Comment by jmooring** [comment]
@brmassa 

> reopen it please

This issue _is_ open. Are you referring to something else?

**Comment by brmassa** [comment]
My bad. The CXwudi comment fooled me.

**Comment by brmassa** [comment]
@bep , since this issue seems to be abandoned and made `0.123` not backward compatible (which, btw, would be nice to raise the major version number to signal users for the breaking change), what are the possible workarounds? Instead of fixing the app, how could I implement it in the template?

I just need to list the resources in a page, just like `{{ .Resources.ByType "image" }}` would in older versions. But in case that the default language page does not exist. Should I search for the `Resources` from the default language, even the content itself does not exist?

I'm stuck with `0.122` for months since the break. 
Thank you for your assistance.

(default language; `en`)

```tree
.
└── content
    └── posts
        └── my-first-post
            ├── img.png
            └── index.de.md
```

**Comment by brmassa** [comment]
Yes, `0.123` forward, the `default` language became a `required` language.

## "FIX"

I've managed to fix this bug by creating an `index.md` in the same folder.

```
---
headless: true
---
```

It will make Hugo think that there is a content, but at the end it will not show anything. The downside it that I have to create this file for all previous content.

**Comment by Arty2** [comment]
> The basic multilingual logic for missing translations is, as documented: \"If a string does not have a translation for the current language, Hugo will use the value from the default language. […]

I understand the rationale is to be cautious of unused resources, but as previously noted here, this behavior is counter-intuitive against the i18n defaults.

Plus it may be valid to denote the language in the filename for other resources, but when it comes to images —in my opinion— they shouldn’t need a language indicator, unless they contain text or specific features where their content makes sense to be translated or localized.
