### ISSUE TITLE
Code blocks not rendered correctly in lists

### ISSUE THREAD

**Issue by mobenar** [gohugoio/hugo#2928]
This markdown:

    - Hello<br>
      bla bla
    - Example<br>
      ```javascript
      var message = 'hello';
      console.log(message);
      ```

> The &lt;br&gt; is also needed in Hugo for a line break in the list item, which differs from other generators.

Renders as:

* Hello
  bla bla
* Example
  `javascript var message = 'hello'; console.log(message);`

**Comment by bep** [comment]
Assuming you use Blackfriday, please post an issue here:

https://github.com/russross/blackfriday/issues

And link back to this issue.

**Comment by mobenar** [comment]
[Issue reported to Blackfriday](https://github.com/russross/blackfriday/issues/326)

**Comment by bep** [comment]
You should post the entire description on the BF issue, not just a link back here.

**Comment by kaushalmodi** [comment]
This works

```
- Hello<br>
bla bla

- Example<br>
```javascript
var message = 'hello';
console.log(message);
```

- Hello again!
```

Simply put a white space between each list item. I do not know if this is a hack, or if this is how it supposed to be done. But I have learned doing that by trial and error :)

http://scripter.co/get-current-directory-name-without-path/

**Comment by maueroats** [comment]
Reported a similar/same issue. The hack mentioned above breaks the ordering in an ordered list, so it doesn't really work. Linked issue includes a demo markdown file and says specifically what is wrong in the generated HTML.

https://github.com/russross/blackfriday/issues/392

**Comment by kaushalmodi** [comment]
> The hack mentioned above breaks the ordering in an ordered list, so it doesn't really work. 

??

Works fine for me:
![image](https://user-images.githubusercontent.com/3578197/30678078-d1339bac-9e5d-11e7-96c2-224393eee2af.png)

**Comment by maueroats** [comment]
I see. If you put a newline after the code block but not before it, the numbering is maintained.

If you put an empty line before the code block as well as after, the numbering is not maintained. I don't know if that is expected behavior, but it is certainly surprising to me.

**Comment by kaushalmodi** [comment]
I believe this issue can be closed as `hugo` itself has little to do with it. But the Blackfriday repo issue handling and maintenance is in a sad state .. there has been no activity on the issues posted related to this current issue: https://github.com/russross/blackfriday/issues/326, https://github.com/russross/blackfriday/issues/239, and also [in general][1] (*I have noticed that for quite a few months*)! 😞 

[1]: https://github.com/russross/blackfriday/pulse/monthly

**Comment by maueroats** [comment]
Workaround I currently use: 8 space indentation to get the code block. {{< highlight ... >}} to get syntax highlighting if I want it that badly.

Close it for hugo.

**Comment by aignas** [comment]
This has been fixed recently: https://github.com/russross/blackfriday/pull/521

**Comment by mohnjatthews** [comment]
Did the update from BlackFriday ever get merged into Hugo? I'm still seeing weird code-block stuff.

![Screen Shot 2019-05-28 at 12 55 07 PM](https://user-images.githubusercontent.com/9611008/58496460-f2f03380-8147-11e9-9089-3d324c27ddc7.png)

Here's my Markdown for the image above:

```markdown
#### Run the Installation

1. Connect to your machine via SSH or open a terminal if you are working on a local installation.
2. Change to your root `~` directory and update your system:

    ```bash
    cd ~
    sudo apt update -y && sudo apt upgrade -y
    ```

3. Download the latest [package](https://github.com/exampleproject/releases) to your computer if you haven't already. You can also use `wget` if you'd prefer:

    ```bash
    wget https://github.com/exampleproject/release.tar.bz2
    ```

4. Unzip the package and move the directory to your home `~` directory:
```

**Comment by zilongshanren** [comment]
I'm also face this issue, it seems be fixed in the blackfriday, but in hugo this issue still exists.

**Comment by thomask** [comment]
Yup, same issue here

**Comment by jmooring** [comment]
No longer reproducible with v0.82 using default markdown renderer (Goldmark).
