### ISSUE TITLE
Add shortcode to link to static files

### ISSUE THREAD

**Issue by Shadow53** [gohugoio/hugo#3732]
(Examples use a file at `/static/path/to/image.jpg`)

In order to get links to static files in content files, we need to either
1. Write a path relative to the current directory, with `../` and the like, so a file at `content/section/subsection/page.md` would need `../../../path/to/image.jpg`
1. Prefix the path with a leading `/`, which causes the path to resolve to `example.com/path/to/image.jpg'

(Leaving off the leading `/` causes the link to resolve relative to the current page, which is undesirable)

The first is a pain to have to do, and the second only works if the `baseURL` is `example.com`. `example.com/subdir/` will still resolve the link to `example.com/path/to/image.jpg', which won't exist.

I propose having a shortcode similar to the existing `ref` and `relref` that takes a path or URL, processes it through `absURL` or `absLangURL`, and returns that to the markdown. It would look nicer than the first alternative above and resolve correctly with subdirectories, unlike the second.

**What I came up with:**
Syntax: `{{< static "/path/to/image.jpg" >}}`
Code (ignores leading `/`):
```
{{- .Scratch.Set "path" (.Get 0) -}}
{{- if hasPrefix (.Scratch.Get "path") "/" -}}
  {{- .Scratch.Set "path" (slicestr (.Scratch.Get "path") 1) -}}
{{- end -}}
{{- .Scratch.Get "path" | absLangURL -}}
```

Without stripping the leading `/`, the code would just be:
```
{{- .Get 0 | absLangURL -}}
```

**Comment by bep** [comment]
This situation will improve once #3651 is out, but it is still a good idea.

We should consider naming it similar to `ref` and `relref`: `staticRef`, `staticRelref`?

**Comment by gotgenes** [comment]
I arrived at this issue searching for a safe way to link to a static asset from within any page. #3651 was resolved, however, I don't see the way that resolves this issue. Would any project maintainers please comment here if it does?

**Comment by ComFreek** [comment]
Unfortunately, there still doesn't seem an official one-liner for linking to static assets.

**Comment by toman** [comment]
The activity here seems to indicate that page bundles are the official answer. However, that's only a good solution if the asset is used on just one set of pages. If it's used in more than one place on the site then you have to replicate the asset wherever it's needed, which isn't very satisfactory, or come back to the original question, linking to static assets in content.
