### ISSUE TITLE
Matching i18n etc. do not work in ignoreFiles 

### ISSUE THREAD

**Issue by zner0L** [gohugoio/hugo#4872]
Until version 0.42 I used a simple regex to ignore all .json files in the translation directory: `i18n/.+\\.json$`. It seems like the the new virtual filesystem broke this behavior. Is there a new and preferred way to do this now or can this be fixed?
Regexes without directories seem to work (e.g. `.+\\.json$`).

**Comment by bep** [comment]
A note on this topic: We have now merged these different Hugo folders (i18n, layouts) into separate roots as a composite of project + themes. Which is obviously simpler than having to do "check first the project and then the theme" logic every time this is needed.

But with the upcoming Hugo release, we should be able to match against the real filename in this case, which may what we want. But this will have to wait a little.

**Comment by rlenferink** [comment]
Hi all,

Is there already some progress for this? At k8s we're still having the following problem:
https://discourse.gohugo.io/t/ignorefiles-and-i18n-expected-behavior/15097

We're using `OWNERS` files for determining whether someone can give his/her approval for a specific file. We want to add this `OWNERS` file to the `i18n/` directory as well, however won't ignore the file and will give the following error message:

```text
ERROR 2019/04/30 18:02:43 "/src/i18n/OWNERS:1:1": failed to load translations: failed to unmarshal OWNERS: unsupported file extension
```

We're having the following ignoreFiles in place, which perfectly ignores the OWNERS files from other directories:
```text
ignoreFiles = [ "^OWNERS$", "README[-]+[a-z]*\\.md", "^node_modules$", "content/en/docs/doc-contributor-tools" ]
```

**Comment by jmooring** [comment]
See [relevant documentation](https://gohugo.io/getting-started/configuration/#ignore-content-and-data-files-when-rendering):

> To exclude specific files from the `content`, `data`, and `i18n` directories when rendering your site, set `ignoreFiles` to one or more regular expressions to match against the **absolute** file path.

Examples to exclude `i18n/OWNERS`:

```toml
ignoreFiles = ['/OWNERS$']
ignoreFiles = ['i18n/OWNERS$']
ignoreFiles = ['/i18n/OWNERS$']
ignoreFiles = ['^/home/user/project/i18n/OWNERS$']
```

This may not have worked when the issue was created, but it works as desired in v0.111.3.
