### ISSUE TITLE
hugo is not building the resource files when changes occur either on scss or js files

### ISSUE THREAD

**Issue by valterbarros** [gohugoio/hugo#7873]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version

Hugo Static Site Generator v0.76.5-60F0725B linux/amd64 BuildDate: 2020-10-14T15:15:49Z

</pre>

### Does this issue reproduce with the latest release?

yes

I'm using hugo-cli lib to build my site https://github.com/nikku/hugo-cli/issues/34, I installed hugo via brew, and that build the resources files and the version is the same from downloaded hugo-cli

I already tried to install the `hugo_0.76.5_Linux-64bit.deb` package and that doesn't work too, hugo-cli download .deb file too and use to build.

**Comment by gwd0715** [comment]
Same issue here.
The SCSS will compile when I start the server or a hard server restart

**Comment by valterbarros** [comment]
@gwd0715 I fixed my issue using the extended version, https://github.com/gohugoio/hugo#fetch-from-github see the hugo doc to more info. see the issue too https://github.com/nikku/hugo-cli/issues/34

**Comment by gwd0715** [comment]
> @valterbarros  I fixed my issue using the extended version, https://github.com/gohugoio/hugo#fetch-from-github see the hugo doc to more info. see the issue too [nikku/hugo-cli#34](https://github.com/nikku/hugo-cli/issues/34)

My hugo version is the extended version and the problem still exists.
