### ISSUE TITLE
Muted black and white levels when resizing WebP images

### ISSUE THREAD

**Issue by aureliendossantos** [gohugoio/hugo#8879]
Image Processing works well when the source image is a png or a jpg, but when it's a webp, blacks and whites appear toned down. At first I wondered if it was a problem similar to #8298, but that issue has to do with non-sRGB images, which is not the case here. My webp is sRGB (unless `cwebp` is fooling me) and the problem only appears with webp images.

### What version of Hugo are you using (`hugo version`)?

<pre>
hugo v0.87.0-B0C541E4+extended windows/amd64 BuildDate=2021-08-03T10:57:28Z VendorInfo=gohugoio
</pre>

### Example

Here's a sRGB webp image I want to process. You can clearly see the deep blacks in the trees and the bright clouds.
(How I created this image: I first exported it as a sRGB PNG in Adobe Lightroom then converted it with `cwebp`. The problem would have been the same if I directly exported the webp with, say, GIMP)

![Photo](https://aureliendossantos.github.io/randonnees/7-villages-vallee-d-aspe/66.webp)
You can download the original [here](https://aureliendossantos.github.io/randonnees/7-villages-vallee-d-aspe/66.webp).

Here's the image processed by Hugo with `.Resize`. No matter the targeted format (webp, png, jpg) or the targeted size, it will always have these muted blacks and whites.

![](https://user-images.githubusercontent.com/31006039/129012047-d9b1152a-c8c7-4978-980a-3f9827a70136.png)

This is `66_hu491b7a84666ef3266e0bfb2f80fb050e_290232_1600x0_resize_q75_h2_linear_2.webp` (converted in png so I could upload it on GitHub)

**Comment by ptgott** [comment]
I've reworked my [integration test](https://github.com/ptgott/hugo/blob/2b533111c7258d8a17c295ea912f389a6ca818a1/hugolib/image_test.go#L255). Now it loads a real webp image using the sRGB color space (created via Gimp). The [image](https://raw.githubusercontent.com/ptgott/hugo/2b533111c7258d8a17c295ea912f389a6ca818a1/hugolib/testdata/color-test.webp) uses dark and light colors from the original image in this thread, with one color per half to make it easy to compare colors before and after resizing. 

The test copies the image to the **assets/images** directory, then resizes a template to `10x10 png`. Unfortunately, I've failed to reproduce this issue: the colors on either side of the resized image are the same as the ones in the original image. @aureliendossantos is there anything the test could be missing here? Thanks!

**Comment by bep** [comment]
I have tested the above web image in a standalone Go program, by just decoding the webp and encoding it directly as JPEG. And the result is the "dull blacks" as reported above. This is, of course, narrows down the problem and makes it easier to pin down. Not sure what it is, if it's a bug in the Webp decoder we use. We use a Go native decoder. We use the `libweb` C encoder (because there are no Go encoder). We could, in theory, use the C decoder, but that opens up a massive set of security questions that I'm not prepared to ask/answer.


```bash
package main

import (
	"image"
	"log"
	"os"
	"path/filepath"

	"image/jpeg"

	_ "golang.org/x/image/webp"
)

func main() {
	dir := "/Users/bep/dev/sites/hugotest/assets/images/misc/"
	filename := filepath.Join(dir, "webp-muted.webp")
	outfilename := filepath.Join(dir, "webp-muted.jpg")

	f, err := os.Open(filename)
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	img, _, err := image.Decode(f)
	if err != nil {
		log.Fatal(err)
	}

	outFile, err := os.Create(outfilename)
	if err != nil {
		log.Fatal(err)
	}
	defer outFile.Close()

	if err := jpeg.Encode(outFile, img, nil); err != nil {
		log.Fatal(err)
	}
}

```

**Comment by bep** [comment]
OK, the issue is reported upstream here: https://github.com/golang/go/issues/40173

**Comment by savtrip** [comment]
@aureliendossantos Did you end up finding a work around for this issue?

**Comment by savtrip** [comment]
@bep One option is to switch the library to another Go Lang library from the community.

For example: https://github.com/chai2010/webp

**Comment by aureliendossantos** [comment]
> @aureliendossantos Did you end up finding a work around for this issue?

No, I didn't yet!

**Comment by msilber** [comment]
Is it possible that his is due to color space conversion?

**Comment by xianfei** [comment]
I fixed it via replacing "golang.org/x/image/webp" with "github.com/chai2010/webp".
You can try it [https://github.com/xianfei/hugo](https://github.com/xianfei/hugo)
![WX20230205-202245@2x](https://user-images.githubusercontent.com/8101613/216819820-4ebe9d37-772a-46ce-93ed-e4f5341ea265.png)
![WX20230205-201944@2x](https://user-images.githubusercontent.com/8101613/216819822-0879b262-cee4-4f81-a445-8aeb24c9405f.png)

**Comment by savtrip** [comment]
Hey @bep it seems this issue was not resolved upstream, is it possible to switch to another library such as: https://github.com/chai2010/webp? Or any other solution that uses an FFI around CWEPB decode? 

I saw your previous comment that said you weren't prepared to ask/answer the implications of an external binary, is this still the position?

If not I am more than happy to contribute and make a pull request.

Also, thank you for maintaining Hugo, it is much appreciated.

**Comment by slnc** [comment]
I'm also affected by this. 

@bep upstream has had the bug open for 4y, so it doesn't seem like a priority for them, and there are working alternatives like @savtrip mentioned.

For people like me who rely on Github Actions to run and deploy hugo sites, the options I see don't look great:

a) maintain a fork of hugo and a corresponding binary that uses https://github.com/chai2010/webp for Github Action publish workflows (expensive to maintain)
b) don't use WebP (hurts site visitors and would double my storage requirements)
c) don't use .Resize at all (hurts site visitors and increases storage costs)
d) create resized images outside of hugo before hugo runs (expensive to maintain)

On the other hand, I understand that https://github.com/chai2010/webp might be slower, and that depending on a binary like `cwebp` doesn't look appealing.

Do we have any other alternatives? Would allowing users to use https://github.com/chai2010/webp through an experimental flag be acceptable?

**Comment by autay27** [comment]
Yes, this is affecting me too. I would have liked if Hugo would at least display a warning about this issue when rendering my site, so I would know to seek alternatives.

**Comment by Berny23** [comment]
I guess I'm also affected. JPEGs look exactly the same in the thumbnails, but WEBP files look washed out in the thumbnail.

Example site (the images at the bottom are JPEGs): https://berny23.de/warframe/

**Comment by cpbotha** [comment]
I have modified my srcset figure shortcode to work around this regrettable golang bug: https://gist.github.com/cpbotha/deb310eed14308fe26f7b7d0fabeb34d?permalink_comment_id=5299293#gistcomment-5299293

In short, the shortcode links webp images and resized images everywhere, but uses the .png/.jpg version of the image in question (supplied by the user) for all of its resizing.
